name: jusibe
description: Dartlang Client Library for Jusibe SMS REST API Service https://jusibe.com
version: 0.1.1
author: Fabusuyi Ayodeji <thedejifab@outlook.com>
homepage: https://github.com/thedejifab/jusibe_dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies: 
  dio: ^2.0.5
  meta: ^1.1.7
dev_dependencies: 
  build_runner: ^0.9.1
  console: ^3.0.0
  test: ^1.3.0