name: jusibe
description: A Jusibe client library for Dart.
version: 0.1.0
author: Fabusuyi Ayodeji <thedejifab@outlook.com>
homepage: https://github.com/thedejifab/jusibe_dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies: 
  dio: ^2.0.5
dev_dependencies: 
  build_runner: ^0.9.1
  console: ^3.0.0
  test: ^1.3.0